-- ============================================================
-- Migration: AI Diet Features
-- Created: 2026-03-01
-- Description: Adds columns for AI-generated diet plans and
--              photo-based meal tracking
-- ============================================================

-- Track whether a diet plan was generated by AI
ALTER TABLE public.diet_plans ADD COLUMN IF NOT EXISTS is_ai_generated BOOLEAN DEFAULT false;

-- Track whether a member has already used their one-time AI plan generation
ALTER TABLE public.members ADD COLUMN IF NOT EXISTS ai_plan_used BOOLEAN DEFAULT false;

-- Track whether a meal was added via photo analysis
ALTER TABLE public.meal_plans ADD COLUMN IF NOT EXISTS image_analyzed BOOLEAN DEFAULT false;
