-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.announcements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  gym_id uuid NOT NULL,
  title character varying NOT NULL,
  message text NOT NULL,
  type character varying DEFAULT 'info'::character varying CHECK (type::text = ANY (ARRAY['info'::character varying, 'warning'::character varying, 'emergency'::character varying, 'holiday'::character varying, 'closure'::character varying]::text[])),
  is_active boolean DEFAULT true,
  starts_at timestamp with time zone DEFAULT now(),
  ends_at timestamp with time zone,
  notify_members boolean DEFAULT false,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT announcements_pkey PRIMARY KEY (id),
  CONSTRAINT announcements_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id)
);
CREATE TABLE public.check_ins (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  gym_id uuid NOT NULL,
  member_id uuid,
  qr_code_id uuid,
  scan_id uuid,
  check_in_at timestamp with time zone DEFAULT now(),
  check_out_at timestamp with time zone,
  duration_minutes integer DEFAULT (EXTRACT(epoch FROM (check_out_at - check_in_at)) / (60)::numeric),
  notes text,
  tags ARRAY,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT check_ins_pkey PRIMARY KEY (id),
  CONSTRAINT check_ins_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id),
  CONSTRAINT check_ins_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT check_ins_qr_code_id_fkey FOREIGN KEY (qr_code_id) REFERENCES public.qr_codes(id),
  CONSTRAINT check_ins_scan_id_fkey FOREIGN KEY (scan_id) REFERENCES public.scans(id)
);
CREATE TABLE public.daily_analytics (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  gym_id uuid NOT NULL,
  date date NOT NULL,
  total_scans integer DEFAULT 0,
  unique_visitors integer DEFAULT 0,
  new_members integer DEFAULT 0,
  returning_members integer DEFAULT 0,
  peak_hour integer,
  scans_by_hour jsonb DEFAULT '{}'::jsonb,
  top_device text,
  devices_breakdown jsonb DEFAULT '{}'::jsonb,
  top_city text,
  cities_breakdown jsonb DEFAULT '{}'::jsonb,
  conversions integer DEFAULT 0,
  conversion_rate numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT daily_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT daily_analytics_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id)
);
CREATE TABLE public.diet_plans (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  gym_id uuid NOT NULL,
  member_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  target_calories integer,
  target_protein integer,
  target_carbs integer,
  target_fat integer,
  is_active boolean DEFAULT true,
  start_date date,
  end_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_ai_generated boolean DEFAULT false,
  CONSTRAINT diet_plans_pkey PRIMARY KEY (id),
  CONSTRAINT diet_plans_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id),
  CONSTRAINT diet_plans_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id)
);
CREATE TABLE public.exercise_library (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  gym_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  category text,
  equipment ARRAY,
  instructions text,
  video_url text,
  image_url text,
  is_custom boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT exercise_library_pkey PRIMARY KEY (id),
  CONSTRAINT exercise_library_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id)
);
CREATE TABLE public.exercise_sets (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  session_exercise_id uuid NOT NULL,
  set_number integer NOT NULL,
  weight numeric,
  reps integer,
  duration_seconds integer,
  completed boolean DEFAULT false,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT exercise_sets_pkey PRIMARY KEY (id),
  CONSTRAINT exercise_sets_session_exercise_id_fkey FOREIGN KEY (session_exercise_id) REFERENCES public.session_exercises(id)
);
CREATE TABLE public.expenses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  gym_id uuid NOT NULL,
  category character varying NOT NULL,
  description text,
  amount numeric NOT NULL,
  currency character varying DEFAULT 'INR'::character varying,
  expense_date date NOT NULL,
  is_recurring boolean DEFAULT false,
  recurrence_frequency character varying CHECK (recurrence_frequency::text = ANY (ARRAY['monthly'::character varying, 'quarterly'::character varying, 'yearly'::character varying]::text[])),
  staff_id uuid,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT expenses_pkey PRIMARY KEY (id),
  CONSTRAINT expenses_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id),
  CONSTRAINT expenses_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.staff(id)
);
CREATE TABLE public.feedback_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  gym_id uuid NOT NULL,
  member_id uuid NOT NULL,
  sent_at timestamp with time zone DEFAULT now(),
  responded_at timestamp with time zone,
  response_text text,
  response_rating integer CHECK (response_rating >= 1 AND response_rating <= 5),
  status character varying DEFAULT 'sent'::character varying CHECK (status::text = ANY (ARRAY['sent'::character varying, 'responded'::character varying, 'expired'::character varying]::text[])),
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT feedback_requests_pkey PRIMARY KEY (id),
  CONSTRAINT feedback_requests_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id),
  CONSTRAINT feedback_requests_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id)
);
CREATE TABLE public.gym_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  gym_id uuid NOT NULL,
  member_id uuid NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  review_text text,
  is_public boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gym_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT gym_reviews_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id),
  CONSTRAINT gym_reviews_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id)
);
CREATE TABLE public.gym_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  gym_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role character varying NOT NULL CHECK (role::text = ANY (ARRAY['owner'::character varying, 'co_owner'::character varying, 'trainer'::character varying, 'receptionist'::character varying, 'viewer'::character varying]::text[])),
  permissions jsonb DEFAULT '{}'::jsonb,
  invited_by uuid,
  invited_at timestamp with time zone DEFAULT now(),
  accepted_at timestamp with time zone,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gym_roles_pkey PRIMARY KEY (id),
  CONSTRAINT gym_roles_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id),
  CONSTRAINT gym_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT gym_roles_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id)
);
CREATE TABLE public.gyms (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  owner_id uuid NOT NULL,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  logo_url text,
  cover_image_url text,
  address text,
  city text,
  state text,
  zip_code text,
  country text DEFAULT 'US'::text,
  phone text,
  email text,
  website text,
  timezone text DEFAULT 'America/New_York'::text,
  currency text DEFAULT 'USD'::text,
  settings jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gyms_pkey PRIMARY KEY (id),
  CONSTRAINT gyms_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.meal_plans (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  diet_plan_id uuid NOT NULL,
  scheduled_for timestamp with time zone NOT NULL,
  scheduled_date date NOT NULL,
  meal_type text NOT NULL CHECK (meal_type = ANY (ARRAY['breakfast'::text, 'lunch'::text, 'dinner'::text, 'snack'::text])),
  name text NOT NULL,
  description text,
  calories integer,
  protein integer,
  carbs integer,
  fat integer,
  notes text,
  completed boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  image_analyzed boolean DEFAULT false,
  CONSTRAINT meal_plans_pkey PRIMARY KEY (id),
  CONSTRAINT meal_plans_diet_plan_id_fkey FOREIGN KEY (diet_plan_id) REFERENCES public.diet_plans(id)
);
CREATE TABLE public.members (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  gym_id uuid,
  email text,
  phone text,
  full_name text,
  avatar_url text,
  member_since date DEFAULT CURRENT_DATE,
  membership_tier text DEFAULT 'visitor'::text,
  birth_date date,
  gender text,
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  is_verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  membership_status text CHECK (membership_status IS NULL OR (membership_status = ANY (ARRAY['active'::text, 'expired'::text, 'suspended'::text, 'cancelled'::text, 'pending'::text, 'trial'::text]))),
  subscription_plan text CHECK (subscription_plan IS NULL OR (subscription_plan = ANY (ARRAY['1_month'::text, '3_months'::text, '6_months'::text, '1_year'::text, 'custom'::text]))),
  subscription_start_date timestamp with time zone,
  auth_user_id uuid,
  portal_pin text,
  pin_created_at timestamp with time zone,
  last_pin_sent_at timestamp with time zone,
  is_blacklisted boolean DEFAULT false,
  blacklisted_at timestamp with time zone,
  blacklist_reason text,
  subscription_end_date timestamp with time zone,
  ai_plan_used boolean DEFAULT false,
  CONSTRAINT members_pkey PRIMARY KEY (id),
  CONSTRAINT members_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id),
  CONSTRAINT members_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  gym_id uuid,
  user_id uuid,
  type text NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  gym_id uuid NOT NULL,
  member_id uuid NOT NULL,
  amount numeric NOT NULL,
  currency text NOT NULL DEFAULT 'USD'::text,
  type text NOT NULL DEFAULT 'subscription'::text,
  status text NOT NULL DEFAULT 'completed'::text,
  description text,
  payment_date timestamp with time zone NOT NULL DEFAULT now(),
  period_start date,
  period_end date,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  payment_method text NOT NULL DEFAULT 'cash'::text,
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id),
  CONSTRAINT payments_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id)
);
CREATE TABLE public.personal_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  gym_id uuid NOT NULL,
  member_id uuid NOT NULL,
  exercise_name character varying NOT NULL,
  exercise_id uuid,
  weight numeric NOT NULL,
  reps integer DEFAULT 1,
  recorded_at timestamp with time zone DEFAULT now(),
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT personal_records_pkey PRIMARY KEY (id),
  CONSTRAINT personal_records_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id),
  CONSTRAINT personal_records_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT personal_records_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercise_library(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL,
  full_name text,
  phone text,
  avatar_url text,
  company_name text,
  business_address text,
  subscription_tier text DEFAULT 'free'::text CHECK (subscription_tier = ANY (ARRAY['free'::text, 'starter'::text, 'pro'::text, 'enterprise'::text])),
  subscription_status text DEFAULT 'active'::text CHECK (subscription_status = ANY (ARRAY['active'::text, 'cancelled'::text, 'past_due'::text])),
  subscription_expires_at timestamp with time zone,
  onboarding_completed boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.qr_codes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  gym_id uuid NOT NULL,
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  label text,
  type text DEFAULT 'check-in'::text CHECK (type = ANY (ARRAY['check-in'::text, 'equipment'::text, 'class'::text, 'promotion'::text, 'custom'::text])),
  redirect_url text,
  design_settings jsonb DEFAULT '{"frameStyle": "square", "logoEnabled": true, "primaryColor": "#000000", "backgroundColor": "#FFFFFF"}'::jsonb,
  scan_limit integer,
  expires_at timestamp with time zone,
  is_active boolean DEFAULT true,
  total_scans integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT qr_codes_pkey PRIMARY KEY (id),
  CONSTRAINT qr_codes_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id)
);
CREATE TABLE public.referrals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  gym_id uuid NOT NULL,
  referrer_member_id uuid NOT NULL,
  referred_member_id uuid NOT NULL,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'converted'::character varying, 'expired'::character varying, 'rewarded'::character varying]::text[])),
  bonus_type character varying,
  bonus_value numeric,
  bonus_applied_at timestamp with time zone,
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT referrals_pkey PRIMARY KEY (id),
  CONSTRAINT referrals_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id),
  CONSTRAINT referrals_referrer_member_id_fkey FOREIGN KEY (referrer_member_id) REFERENCES public.members(id),
  CONSTRAINT referrals_referred_member_id_fkey FOREIGN KEY (referred_member_id) REFERENCES public.members(id)
);
CREATE TABLE public.routine_exercises (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  routine_id uuid NOT NULL,
  exercise_id uuid NOT NULL,
  order_index integer NOT NULL DEFAULT 0,
  sets integer DEFAULT 3,
  reps integer,
  duration_seconds integer,
  rest_seconds integer DEFAULT 60,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT routine_exercises_pkey PRIMARY KEY (id),
  CONSTRAINT routine_exercises_routine_id_fkey FOREIGN KEY (routine_id) REFERENCES public.workout_routines(id),
  CONSTRAINT routine_exercises_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercise_library(id)
);
CREATE TABLE public.scans (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  qr_code_id uuid,
  gym_id uuid NOT NULL,
  member_id uuid,
  scanned_at timestamp with time zone DEFAULT now(),
  scan_type text DEFAULT 'check-in'::text CHECK (scan_type = ANY (ARRAY['check-in'::text, 'equipment'::text, 'class'::text, 'promotion'::text])),
  ip_address inet,
  user_agent text,
  device_type text,
  browser text,
  os text,
  country text,
  city text,
  latitude numeric,
  longitude numeric,
  referrer text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  session_duration_seconds integer,
  converted boolean DEFAULT false,
  conversion_type text,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT scans_pkey PRIMARY KEY (id),
  CONSTRAINT scans_qr_code_id_fkey FOREIGN KEY (qr_code_id) REFERENCES public.qr_codes(id),
  CONSTRAINT scans_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id),
  CONSTRAINT scans_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id)
);
CREATE TABLE public.session_exercises (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  session_id uuid NOT NULL,
  exercise_id uuid NOT NULL,
  order_index integer NOT NULL,
  completed boolean DEFAULT false,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT session_exercises_pkey PRIMARY KEY (id),
  CONSTRAINT session_exercises_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.workout_sessions(id),
  CONSTRAINT session_exercises_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercise_library(id)
);
CREATE TABLE public.staff (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  gym_id uuid NOT NULL,
  full_name character varying NOT NULL,
  role character varying NOT NULL,
  phone character varying,
  email character varying,
  salary numeric DEFAULT 0,
  salary_frequency character varying DEFAULT 'monthly'::character varying CHECK (salary_frequency::text = ANY (ARRAY['monthly'::character varying, 'weekly'::character varying, 'daily'::character varying]::text[])),
  hire_date date DEFAULT CURRENT_DATE,
  is_active boolean DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT staff_pkey PRIMARY KEY (id),
  CONSTRAINT staff_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id)
);
CREATE TABLE public.webhook_events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  gym_id uuid,
  event_type text NOT NULL,
  payload jsonb NOT NULL,
  processed boolean DEFAULT false,
  processed_at timestamp with time zone,
  error_message text,
  retry_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT webhook_events_pkey PRIMARY KEY (id),
  CONSTRAINT webhook_events_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id)
);
CREATE TABLE public.workout_routines (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  gym_id uuid NOT NULL,
  member_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  schedule ARRAY,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workout_routines_pkey PRIMARY KEY (id),
  CONSTRAINT workout_routines_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id),
  CONSTRAINT workout_routines_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id)
);
CREATE TABLE public.workout_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  gym_id uuid NOT NULL,
  member_id uuid NOT NULL,
  routine_id uuid,
  check_in_id uuid,
  started_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  duration_minutes integer,
  notes text,
  status text DEFAULT 'in_progress'::text CHECK (status = ANY (ARRAY['in_progress'::text, 'completed'::text, 'abandoned'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workout_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT workout_sessions_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id),
  CONSTRAINT workout_sessions_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT workout_sessions_routine_id_fkey FOREIGN KEY (routine_id) REFERENCES public.workout_routines(id),
  CONSTRAINT workout_sessions_check_in_id_fkey FOREIGN KEY (check_in_id) REFERENCES public.check_ins(id)
);